server.port =${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_USER}
spring.datasource.username=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

